#include <stdio.h>
int k ;
int hail(unsigned long long n);
int main(void)
{
	unsigned long long num;
	int HailstoneNumber;
	while (scanf("%llu", &num)!=EOF&&num>0)
	{
		k = 1;
		printf("Hailstone generated by %llu:\n", num);
		if (num == 1)
			;
		if (num != 1)
			printf("%llu ", num);
		HailstoneNumber=hail(num);
		printf("Number of hailstone generated:%d\n\n", HailstoneNumber);
	}
	return 0;
}
int hail(unsigned long long n)
{
	unsigned long long num1;
	if (n == 1)
		printf("%llu\n", n);
	if(n != 1)
	{
		if (n % 2 == 0)
		{
			k++;
			num1 = n / 2;
			if(num1 != 1)
				printf("%llu ", num1);
			hail(num1);
		}
		if (n % 2 != 0)
		{
			k++;
			num1 = 3 * n + 1;
			if (num1 != 1)
				printf("%llu ", num1);
			hail(num1);
		}
	}
	return k;
}